import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home() {
  // Mesh Gradient from customize gradient
  //Icons 8 App to make hero image svg 
  const handleOnBannerBtnClick = () => {

    console.log('Banner Button Click');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View Stores Nearby" handleOnClick={handleOnBannerBtnClick} />
      </main>


    </div>
  )
}
